### ISSUE TITLE
Exception Thrown on Blazor WASM

### ISSUE THREAD

**Issue by LuvForAirplanes** [ekonbenefits/impromptu-interface#43]
I am trying to use this package on my Blazor WASM (client-side) project. The goal is to reflect my database service set out to the client so service methods can be called without calling web APIs.

I'm running into this exception:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot emit a CustomAttribute with argument of type System.RuntimeType.
System.ArgumentException: Cannot emit a CustomAttribute with argument of type System.RuntimeType.
   at System.Reflection.Emit.CustomAttributeBuilder.Initialize(ConstructorInfo con, Object[] constructorArgs, PropertyInfo[] namedProperties, Object[] propertyValues, FieldInfo[] namedFields, Object[] fieldValues)
   at System.Reflection.Emit.CustomAttributeBuilder..ctor(ConstructorInfo con, Object[] constructorArgs)
   at ImpromptuInterface.Build.BuildProxy.BuildTypeHelper(ModuleBuilder builder, Type contextType, Type[] interfaces)
   at ImpromptuInterface.Build.BuildProxy.BuildType(Type contextType, Type mainInterface, Type[] otherInterfaces)
   at ImpromptuInterface.Impromptu.DynamicActLike(Object originalDynamic, Type[] otherInterfaces)
   at ImpromptuInterface.ActLikeCaster.TryConvert(ConvertBinder binder, Object& result)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[Object,IMyInterface](CallSite site, Object arg0)
   at WasmReload.Client.Services.DIService.ResolveCustomersService() in C:\Users\Micah\source\repos\WasmReload\WasmReload\Client\Services\DIService.cs:line 67
   at WasmReload.Client.Pages.Index.OnAfterRender(Boolean firstRender) in c:\Users\Micah\source\repos\WasmReload\WasmReload\Client\Pages\Index.razor:line 17
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleAfterRender.OnAfterRenderAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()
```

And here is my code: (from the front page of the repo)
```
   //Dynamic Expando object
    dynamic expando = new ExpandoObject();
    expando.Prop1 ="Test";
    expando.Prop2 = 42L;
    expando.Prop3 = Guid.NewGuid();
    expando.Meth1 = Return<bool>.Arguments<int>(it => it > 5);
    IMyInterface myInterface = Impromptu.ActLike(expando);
```

**Comment by LuvForAirplanes** [comment]
For others wanting to use this on Blazor client-side, comment out this line and you should be set to go:
https://github.com/ekonbenefits/impromptu-interface/blob/master/ImpromptuInterface/src/EmitProxy/BuildProxy.cs#L332
Actually lines 332-334.

**Comment by jbtule** [comment]
interesting, I don't know why it would be trying to generate a the metadata attribute with a `RuntimeType` as the argument. From the code you provided above it should be trying to emit `[ActLikeProxy(new [] {typeof(IMyInterface)}, typeof(object)]`. But your error says RuntimeType which sounds like what would happen in your other issue #44 calling `typeof(X).GetType()` dynamically.

**Comment by jbtule** [comment]
This works now. Tested on .NET 10, browser-wasm, both ways:

```
runtime: Wasm / .NET 10.0.12
PASS ActLike<IPoco>() emits the proxy type
PASS read a property through the proxy
PASS write a property through the proxy
PASS call a method through the proxy
PASS the proxy carries ActLikeProxyAttribute
PASS a second ActLike reuses the cached type
```

Identical output from a plain `dotnet build` (interpreted) and from `dotnet publish -p:RunAOTCompilation=true`, which also trims (`PublishTrimmed` is `true` there). Run under bun, no browser.

The reported error — *"Cannot emit a CustomAttribute with argument of type System.RuntimeType"* — came from `ActLikeMaker.cs:405`, where the emitted proxy type gets `[ActLikeProxyAttribute(Type[], Type)]`. Mono's Reflection.Emit on wasm used to reject a `Type` argument in an attribute blob; it does not any more, and that line is in the passing run above.

Two things worth knowing if you hit something similar on an older runtime:

- Wasm AOT keeps the interpreter for code that needs a JIT, so `RunAOTCompilation=true` does not by itself rule out proxy emit. Full NativeAOT (a different thing, not available for browser-wasm) would.
- If emitting that attribute ever fails again, it is not load-bearing for `ActLike` itself: it is read only by `GetObjectData` (serialization) and by `PreLoadProxy`/the assembly scan for pre-built proxies. Skipping it on such a runtime would leave the ordinary path working.

Not yet covered: an interface reached only dynamically in a trimmed app — the trimmer cannot see it and would remove its members. That is a trimming question rather than a wasm one, and #48 is the better place for it.

Closing as fixed by the runtime. Reopen with the .NET version if you still see it.
