### ISSUE TITLE
Issue Loading Type Dynamically

### ISSUE THREAD

**Issue by LuvForAirplanes** [ekonbenefits/impromptu-interface#44]
I'm getting his exception when I try to dynamically get a type:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failure has occurred while loading a type.
System.TypeLoadException: Failure has occurred while loading a type.
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at ImpromptuInterface.Build.BuildProxy.BuildTypeHelper(ModuleBuilder builder, Type contextType, Type[] interfaces) in C:\Users\Micah\Downloads\impromptu-interface-master\impromptu-interface-master\ImpromptuInterface\src\EmitProxy\BuildProxy.cs:line 400
   at ImpromptuInterface.Build.BuildProxy.BuildType(Type contextType, Type mainInterface, Type[] otherInterfaces) in C:\Users\Micah\Downloads\impromptu-interface-master\impromptu-interface-master\ImpromptuInterface\src\EmitProxy\BuildProxy.cs:line 148
   at ImpromptuInterface.Impromptu.DynamicActLike(Object originalDynamic, Type[] otherInterfaces) in C:\Users\Micah\Downloads\impromptu-interface-master\impromptu-interface-master\ImpromptuInterface\src\Impromptu.cs:line 159
   at WebApplication1.DIService.ResolveCustomersService() in C:\Users\Micah\Downloads\impromptu-interface-master\impromptu-interface-master\WebApplication1\rvice.cs:line 31
   at WebApplication1.Pages.Index.OnAfterRender(Boolean firstRender) in C:\Users\Micah\Downloads\impromptu-interface-master\impromptu-interface-master\WebApplication1\Pages\Index.razor:line 28
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleAfterRender.OnAfterRenderAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()
```
The exception occurs on this line:
https://github.com/ekonbenefits/impromptu-interface/blob/master/ImpromptuInterface/src/EmitProxy/BuildProxy.cs#L399

And here is my code:
```
var type = typeof(ICustomersService);
var expando = new ExpandoObject() as IDictionary<string, object>;
//expando population code here
dynamic myInterface = Impromptu.DynamicActLike(expando, type.GetType());
```
The reason I have to do type.GetType(), is because the type handed into the method could be anything.

@jbtule is this a bug?

**Comment by jbtule** [comment]
You have type inception.  `type.GetType()` is equivalant to   `typeof(ICustomersService).GetType()` , you end up getting the type of types. you want `Impromptu.DynamicActLike(expando, type );`

**Comment by LuvForAirplanes** [comment]
Understood. The issue is that I'm dynamically resolving the type:
`var type = Type.GetType(any_Stringed_Type_Name_Here);`
then doing:
`Impromptu.DynamicActLike(expando, type.GetType());`

**Comment by LuvForAirplanes** [comment]
Oh, gotcha!!! Wow, I thought I knew C# until I started dabbling in the underlying type system and reflection...
